### ISSUE TITLE
使用cpu时无法运行

### ISSUE THREAD

**Issue by iamsile** [lipiji/hierarchical-encoder-decoder#2]
您好，我用gpu时可以正常运行程序，但当切换到cpu运行程序时，会报如下错误:

我的环境是mac os 10.11, python 2.7

Traceback (most recent call last):
  File "main_minibatch.py", line 30, in <module>
    model = RNN(dim_x, dim_y, hidden_size, cell, optimizer, drop_rate, num_sents)
  File "/Users/xxxx/Downloads/hierarchical-encoder-decoder-master/rnn.py", line 31, in **init**
    self.define_train_test_funcs()
  File "/Users/xxxx/Downloads/hierarchical-encoder-decoder-master/rnn.py", line 108, in define_train_test_funcs
    updates = updates)
  File "/Library/Python/2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1778, in orig_function
    defaults)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1642, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/Library/Python/2.7/site-packages/theano/gof/vm.py", line 1037, in make_all
    no_recycling))
  File "/Library/Python/2.7/site-packages/theano/scan_module/scan_op.py", line 868, in make_thunk
    on_unused_input='ignore')
  File "/Library/Python/2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1778, in orig_function
    defaults)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 1658, in create
    self.return_none, self.output_keys, self)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 417, in **init**
    c.value = value
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 468, in **set**
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/Library/Python/2.7/site-packages/theano/tensor/type.py", line 194, in filter
    " dimension.", data.shape, self.broadcastable)
TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn&grad_of_scan_fn}(Elemwise{maximum,no_inplace}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Subtensor{::int64}.0, Alloc.0, DeepCopyOp.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, GRU_W_xz_WordDecoderLayer__401, GRU_W_hz_WordDecoderLayer__401, GRU_W_xh_WordDecoderLayer__401, GRU_W_xr_WordDecoderLayer__401, GRU_W_hr_WordDecoderLayer__401, GRU_W_hh_WordDecoderLayer__401, WordDecoderLayer_W_hy_401, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, MakeVector{dtype='int32'}.0, MakeVector{dtype='int32'}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0, 0), (True, False), 'Container name "None"')

**Comment by lipiji** [comment]
是的，目前lstm或gru里面存在这个bug。

**Comment by iamsile** [comment]
明白了，多谢您的回复

**Comment by migowei0621** [comment]
你好，我在运行的时候出现了下面这样的问题：
TypeError: Cannot convert Type TensorType(float64, 3D) (of Variable IncSubtensor{Set;:int64:}.0) into Type TensorType(float64, (False, True, False)). You can try to manually convert IncSubtensor{Set;:int64:}.0 into a TensorType(float64, (False, True, False)).
我没有用过Theano, 请问该如何解决？谢谢

**Comment by lipiji** [comment]
@migowei0621    theano的config碰一下，特别是float32
