### ISSUE TITLE
Error: "Non-unit value on shape on a broadcastable dimension"

### ISSUE THREAD

**Issue by albert18711** [lipiji/hierarchical-encoder-decoder#4]
I downloaded the whole code to run on my computer(without any changes)
I encounter the error as follow:
# dic = 130
# features =  130 #labels =  130

compiling...
Traceback (most recent call last):
  File "./main_minibatch.py", line 30, in <module>
    model = RNN(dim_x, dim_y, hidden_size, cell, optimizer, drop_rate, num_sents)
  File "/root/downloads/hierarchical-encoder-decoder-master/rnn.py", line 31, in **init**
    self.define_train_test_funcs()
  File "/root/downloads/hierarchical-encoder-decoder-master/rnn.py", line 114, in define_train_test_funcs
    updates = updates)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 856, in make_thunk
    on_unused_input='ignore')
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 1657, in create
    self.return_none, self.output_keys, self)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 417, in **init**
    c.value = value
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/link.py", line 468, in **set**
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/root/home/anaconda2/envs/theano/lib/python2.7/site-packages/theano/tensor/type.py", line 194, in filter
    " dimension.", data.shape, self.broadcastable)
TypeError: ('The following error happened while compiling the node', for{inplace{0,2,4,5,6,7,},cpu,grad_of_scan_fn&grad_of_scan_fn}(Shape_i{0}.0, InplaceDimShuffle{0,1,x}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Subtensor{::int64}.0, Alloc.0, DeepCopyOp.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, GRU_W_xz_WordDecoderLayer__401, GRU_W_hz_WordDecoderLayer__401, GRU_W_xh_WordDecoderLayer__401, GRU_W_xr_WordDecoderLayer__401, GRU_W_hr_WordDecoderLayer__401, GRU_W_hh_WordDecoderLayer__401, WordDecoderLayer_W_hy_401, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, MakeVector{dtype='int32'}.0, MakeVector{dtype='int32'}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0, 0), (True, False), 'Container name "None"')

I've done some search on the Google, but the suggestion for "non-unit value.." error, which is reinstall theano, didn't work for me.

Could you help me with the error? I tried really hard to solve it by myself, but things just didn't worked well.

**Comment by lipiji** [comment]
@albert18711 　Please compile the code suing GPU.

**Comment by albert18711** [comment]
Thanks for the reply~~
I guess the only solution is to get a gpu as soon as possible.
After all, it's quite hard for deep learning without gpu
